name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AdoptOpenJDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '17'
      - name: Test with Gradle
        working-directory: ./
        run: ./gradlew test
